export const PROJECTS = [
  {
    "id": "devboard",
    "number": "01",
    "name": "DevBoard",
    "tagline": "Kanban + Team Collaboration App",
    "phase": "Phase 3 — Weeks 13–14",
    "weeks": "Weeks 13–14 + 14B (Testing)",
    "color": "#6366f1",
    "status": "not-started",
    "tech": [
      "React",
      "TypeScript",
      "Node.js",
      "Express",
      "PostgreSQL",
      "Prisma",
      "JWT",
      "Socket.io",
      "React Query",
      "Zustand",
      "@dnd-kit",
      "Jest",
      "Supertest",
      "RTL"
    ],
    "milestones": [
      "Project setup: monorepo structure",
      "Auth flow: JWT + refresh tokens + protected routes",
      "Database schema: Users, Projects, Boards, Columns, Cards",
      "Backend CRUD APIs for all entities",
      "Frontend Auth pages with RHF + Zod",
      "Dashboard + Project list with React Query",
      "Kanban board with drag-and-drop (@dnd-kit)",
      "Task detail modal + comments + file upload",
      "Backend tests: auth, routes, Zod validators (Jest + Supertest)",
      "Frontend tests: KanbanBoard, auth redirect (RTL)",
      "GitHub Actions CI/CD pipeline",
      "Deploy: Railway + Vercel",
      "README with screenshots + live URL"
    ]
  },
  {
    "id": "fintrack",
    "number": "02",
    "name": "FinTrack Pro",
    "tagline": "Finance & Budget SaaS",
    "phase": "Phase 4 — Weeks 19–20",
    "weeks": "Weeks 19–20 + 20B (Testing)",
    "color": "#10b981",
    "status": "not-started",
    "tech": [
      "Next.js 14",
      "TypeScript",
      "NextAuth v5",
      "Prisma",
      "Supabase",
      "PostgreSQL",
      "Server Actions",
      "Angular",
      "RxJS",
      "Recharts",
      "jsPDF",
      "Jest",
      "RTL"
    ],
    "milestones": [
      "Next.js 14 + NextAuth (Google OAuth) setup",
      "Database schema: Users, Accounts, Transactions, Categories, Budgets",
      "Dashboard: account balances + recent transactions",
      "Transaction CRUD with Server Actions",
      "Budget management + progress bars + 80% alert",
      "Analytics: spending charts (Recharts), month-over-month",
      "Angular transaction history data grid embedded",
      "Search + filters: date range, category, amount",
      "PDF export (jsPDF)",
      "Responsive mobile design",
      "Unit tests: Prisma services + utility functions (Jest)",
      "Component tests: Dashboard, TransactionList, BudgetCard (RTL)",
      "Deploy: Vercel + README with architecture diagram"
    ]
  },
  {
    "id": "nexaai",
    "number": "03",
    "name": "NexaAI",
    "tagline": "AI-Powered Developer Productivity Platform",
    "phase": "Phase 5 — Weeks 26–30",
    "weeks": "Weeks 26–30 (Full Build)",
    "color": "#f97316",
    "status": "not-started",
    "tech": [
      "Next.js 14",
      "TypeScript",
      "Node.js",
      "PostgreSQL",
      "MongoDB",
      "OpenAI API",
      "Gemini API",
      "pgvector",
      "LangChain.js",
      "Redis",
      "Socket.io",
      "Docker",
      "Kubernetes",
      "Vercel",
      "Railway"
    ],
    "milestones": [
      "Project setup: Next.js 14 + TypeScript + Prisma + PostgreSQL + NextAuth",
      "Schema: Users, Projects, Tasks, Documents, AIInteractions",
      "Feature 1: Smart Kanban board (real-time with Socket.io)",
      "Feature 2: AI Code Review (streaming GPT-4o feedback)",
      "Feature 3: Document Q&A with RAG pipeline",
      "Feature 4: AI Standup Generator (GitHub API + LLM)",
      "Redis caching layer + rate limiting on AI endpoints",
      "Docker Compose: app + postgres + redis + frontend",
      "Kubernetes manifests for all services",
      "CI/CD: GitHub Actions (tests + linting on every PR)",
      "Backend tests: AI service, auth middleware, task CRUD",
      "API tests: all major endpoints (Supertest)",
      "Frontend tests: KanbanBoard, ChatWidget, Dashboard (RTL)",
      "Deploy: Vercel + Railway + Supabase",
      "Architecture diagram + full README",
      "3-minute Loom demo video"
    ]
  }
];
